System check identified some issues:

WARNINGS:
[33;1mreviews.Title.genre: (fields.W340) null has no effect on ManyToManyField.[0m
[31;1mCommandError: Unable to serialize database: cursor "_django_curs_140282745444160_3" does not exist
[0m[{"model": "contenttypes.contenttype", "pk": 1, "fields": {"app_label": "admin", "model": "logentry"}}, {"model": "contenttypes.contenttype", "pk": 2, "fields": {"app_label": "auth", "model": "permission"}}, {"model": "contenttypes.contenttype", "pk": 3, "fields": {"app_label": "auth", "model": "group"}}, {"model": "contenttypes.contenttype", "pk": 4, "fields": {"app_label": "contenttypes", "model": "contenttype"}}, {"model": "contenttypes.contenttype", "pk": 5, "fields": {"app_label": "sessions", "model": "session"}}, {"model": "contenttypes.contenttype", "pk": 6, "fields": {"app_label": "authtoken", "model": "token"}}, {"model": "contenttypes.contenttype", "pk": 7, "fields": {"app_label": "authtoken", "model": "tokenproxy"}}, {"model": "contenttypes.contenttype", "pk": 8, "fields": {"app_label": "reviews", "model": "genre"}}, {"model": "contenttypes.contenttype", "pk": 9, "fields": {"app_label": "reviews", "model": "category"}}, {"model": "contenttypes.contenttype", "pk": 10, "fields": {"app_label": "reviews", "model": "title"}}, {"model": "contenttypes.contenttype", "pk": 11, "fields": {"app_label": "reviews", "model": "review"}}, {"model": "contenttypes.contenttype", "pk": 12, "fields": {"app_label": "reviews", "model": "comments"}}, {"model": "contenttypes.contenttype", "pk": 13, "fields": {"app_label": "users", "model": "user"}}